//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMISOR
    {
        public int IdEmisor { get; set; }
        public string Descripcion { get; set; }
        public int IdTipoEmisor { get; set; }
        public Nullable<bool> Mostrar { get; set; }
    
        public virtual TIPOEMISOR TIPOEMISOR { get; set; }
    }
}
