//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_ROL
    {
        public int Id { get; set; }
        public int IdMenu { get; set; }
        public int IdRol { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
