//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class META_VENTA
    {
        public int IdMetaVenta { get; set; }
        public int Mes { get; set; }
        public int Anio { get; set; }
        public int idTipoEmisor { get; set; }
        public decimal Monto { get; set; }
    
        public virtual TIPOEMISOR TIPOEMISOR { get; set; }
    }
}
