//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCUPACION_ARCHIVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCUPACION_ARCHIVO()
        {
            this.OCUPACION = new HashSet<OCUPACION>();
        }
    
        public int IdOcupacionArchivo { get; set; }
        public string NombreArchivo { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public System.DateTime HoraCarga { get; set; }
        public System.DateTime FechaArchivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCUPACION> OCUPACION { get; set; }
    }
}
