//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCUPACION_RUTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCUPACION_RUTA()
        {
            this.OCUPACION_SEGMENTO = new HashSet<OCUPACION_SEGMENTO>();
            this.OCUPACION_META = new HashSet<OCUPACION_META>();
        }
    
        public int IdOcupacionRuta { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionLarga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCUPACION_SEGMENTO> OCUPACION_SEGMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCUPACION_META> OCUPACION_META { get; set; }
    }
}
