//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCUPACION
    {
        public int idOcupacion { get; set; }
        public int IdOcupacionArchivo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string DiaSemana { get; set; }
        public string Vuelo { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public int NLG { get; set; }
        public string CAB { get; set; }
        public int AU { get; set; }
        public int BS { get; set; }
        public int OS { get; set; }
        public int SS { get; set; }
        public int ABS { get; set; }
        public int SA { get; set; }
    
        public virtual OCUPACION_ARCHIVO OCUPACION_ARCHIVO { get; set; }
    }
}
