//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTA_MERCADO
    {
        public int IdRutaMercado { get; set; }
        public int IdRuta { get; set; }
        public string TramoRutaMercado { get; set; }
    
        public virtual RUTA RUTA { get; set; }
    }
}
