//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOLADOS
    {
        public int IdVolado { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
        public string Vuelo { get; set; }
        public string OrigenVenta { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string Equipo { get; set; }
        public string Matricula { get; set; }
        public Nullable<int> Demora { get; set; }
        public string PaisEmision { get; set; }
        public string Emisor { get; set; }
        public string Agente { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<System.DateTime> FechaVueloReal { get; set; }
        public Nullable<System.DateTime> FechaVueloProgramada { get; set; }
        public string Documento { get; set; }
        public Nullable<decimal> Boleto { get; set; }
        public Nullable<int> Fim { get; set; }
        public Nullable<int> Cupon { get; set; }
        public string TipoPasajero { get; set; }
        public string Pasajero { get; set; }
        public string Contacto { get; set; }
        public string Clase { get; set; }
        public string TarifaBase { get; set; }
        public string TourCode { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string PeriodoFi { get; set; }
        public string FiMoneda { get; set; }
        public string FiImporte { get; set; }
        public string Localizador { get; set; }
        public string Aerolinea { get; set; }
        public string MonedaLocal { get; set; }
        public Nullable<decimal> ImporteLocal { get; set; }
        public string Endoso { get; set; }
        public string InfoAdicionalFc { get; set; }
        public string Sac { get; set; }
        public string MonedaQ { get; set; }
        public string ImporteQ { get; set; }
        public string MonedaQI { get; set; }
        public string ImporteQLocal { get; set; }
        public Nullable<int> IdVoladosKiuAdminFile { get; set; }
    
        public virtual AERONAVES AERONAVES { get; set; }
    }
}
