//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOLADOS_SEGMENTO
    {
        public int IdVoladoSegmentos { get; set; }
        public int IdVoladoRuta { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<int> Tramo { get; set; }
    
        public virtual VOLADOS_RUTA VOLADOS_RUTA { get; set; }
    }
}
