//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOLADOS_RUTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOLADOS_RUTA()
        {
            this.VOLADOS_META = new HashSet<VOLADOS_META>();
            this.VOLADOS_SEGMENTO = new HashSet<VOLADOS_SEGMENTO>();
        }
    
        public int IdVoladoRuta { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionLarga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOLADOS_META> VOLADOS_META { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOLADOS_SEGMENTO> VOLADOS_SEGMENTO { get; set; }
    }
}
